// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vueehlhyllcacxdfsybu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1ZWVobGh5bGxjYWN4ZGZzeWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTYwMDAsImV4cCI6MjA2NjU3MjAwMH0.EEf1I5_RNR0CtpaZae3VyZfMwunhc-01dPRHYpVknyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);